[package]
name = "piston"
version = "0.1.0"
authors = ["Tomáš Silber <tomas.silber@outlook.cz>"]

[dependencies]
piston = "0.40.0"
piston_window = "0.87.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.52.0"
piston2d-opengl_graphics = "0.59.0"
rand = "0.6.5"
crossbeam = "0.7.1"
